# SPDX-License-Identifier: Unlicense
# Data only: required paths + unit-surface / SYSTEMS_LEAN_HOST token specs +
# tree-wide banned-jargon walk config. Imported by ./default.nix.
# Edit here when a host stage gains honesty tokens or jargon scope changes.
{
  # Tree-wide jargon walk under src/systems (former check.sh grep -rqi mill).
  # Skip package-local Lake / VCS / cache (same set as emit-wire unit walk).
  jargonWalkRoot = "src/systems";
  jargonWalkSkipDirs = [
    ".lake"
    ".git"
    ".cache"
  ];
  # Match former shell --include set.
  jargonWalkExtensions = [
    ".md"
    ".slake"
    ".lean"
    ".c"
    ".h"
  ];
  # Case-folded substring ban (fail-closed; see default.nix comment on FP risk).
  jargonForbidden = [
    "pole"
    "spine"
  ];

  # Skeleton docs/slake + Lake pin + Mult..SelfHostBody host ladder.
  requiredFiles = [
    "src/systems/README.md"
    "src/systems/check.sh"
    "src/systems/types.md"
    "src/systems/mult.md"
    "src/systems/linear.md"
    "src/systems/erasure.md"
    "src/systems/extract.md"
    "src/systems/host-partial-inventory.md"
    "src/systems/surface-matrix.md"
    "src/systems/self-host.md"
    "src/systems/Types.slake"
    "src/systems/Mult.slake"
    "src/systems/Linear.slake"
    "src/systems/Erasure.slake"
    "src/systems/Extract.slake"
    "src/systems/lakefile.toml"
    "src/systems/lean-toolchain"
    "src/systems/lake-manifest.json"
    "src/systems/SystemsLean.lean"
    "src/systems/SystemsLean/Mult.lean"
    "src/systems/SystemsLean/Linear.lean"
    "src/systems/SystemsLean/Types.lean"
    "src/systems/SystemsLean/IrProgram.lean"
    "src/systems/SystemsLean/Erasure.lean"
    "src/systems/SystemsLean/Extract.lean"
    "src/systems/SystemsLean/IrGraph.lean"
    "src/systems/SystemsLean/HostCompose.lean"
    "src/systems/SystemsLean/EmitPlan.lean"
    "src/systems/SystemsLean/EmitApply.lean"
    "src/systems/SystemsLean/EmitBody.lean"
    "src/systems/SystemsLean/CompilePath.lean"
    "src/systems/SystemsLean/JoinMap.lean"
    "src/systems/SystemsLean/SelfHost.lean"
    "src/systems/SystemsLean/SurfaceMatrix.lean"
    "src/systems/SystemsLean/KernelMult.lean"
    "src/systems/SystemsLean/EmitMult.lean"
    "src/systems/SystemsLean/EmitLinear.lean"
    "src/systems/SystemsLean/FreestandingEmit.lean"
    "src/systems/SystemsLean/ParityMult.lean"
    "src/systems/SystemsLean/KernelLinear.lean"
    "src/systems/SystemsLean/ParityLinear.lean"
    "src/systems/SystemsLean/KernelTypes.lean"
    "src/systems/SystemsLean/ParityTypes.lean"
    "src/systems/SystemsLean/KernelProgram.lean"
    "src/systems/SystemsLean/ParityProgram.lean"
    "src/systems/SystemsLean/KernelEmit.lean"
    "src/systems/SystemsLean/ParityEmit.lean"
    "src/systems/SystemsLean/SelfApply.lean"
    "src/systems/SystemsLean/SelfApplyFs.lean"
    "src/systems/SystemsLean/LlvmHold.lean"
    "src/systems/SystemsLean/InventoryClose.lean"
    "src/systems/SystemsLean/ProductPath.lean"
    "src/systems/SystemsLean/DualResidual.lean"
    "src/systems/SystemsLean/ProbeWire.lean"
    "src/systems/SystemsLean/SpecProof.lean"
    "src/systems/SystemsLean/SelfHostBody.lean"
    # HOST-EMIT-SSOT durable empty-compose / dialect artifact (P2).
    "src/systems/emit/host_emit_body_fragment.ssot.txt"
    # HOST-EMIT-MULT durable Mult product text (SH2).
    "src/systems/emit/host_emit_mult.ssot.txt"
    # HOST-EMIT-LINEAR durable Linear product text.
    "src/systems/emit/host_emit_linear.ssot.txt"
  ];

  hostLeans = [
    "src/systems/SystemsLean/Mult.lean"
    "src/systems/SystemsLean/Linear.lean"
    "src/systems/SystemsLean/Types.lean"
    "src/systems/SystemsLean/IrProgram.lean"
    "src/systems/SystemsLean/Erasure.lean"
    "src/systems/SystemsLean/Extract.lean"
    "src/systems/SystemsLean/IrGraph.lean"
    "src/systems/SystemsLean/HostCompose.lean"
    "src/systems/SystemsLean/EmitPlan.lean"
    "src/systems/SystemsLean/EmitApply.lean"
    "src/systems/SystemsLean/EmitBody.lean"
    "src/systems/SystemsLean/CompilePath.lean"
    "src/systems/SystemsLean/JoinMap.lean"
    "src/systems/SystemsLean/SelfHost.lean"
    "src/systems/SystemsLean/SurfaceMatrix.lean"
    "src/systems/SystemsLean/KernelMult.lean"
    "src/systems/SystemsLean/EmitMult.lean"
    "src/systems/SystemsLean/EmitLinear.lean"
    "src/systems/SystemsLean/FreestandingEmit.lean"
    "src/systems/SystemsLean/ParityMult.lean"
    "src/systems/SystemsLean/KernelLinear.lean"
    "src/systems/SystemsLean/ParityLinear.lean"
    "src/systems/SystemsLean/KernelTypes.lean"
    "src/systems/SystemsLean/ParityTypes.lean"
    "src/systems/SystemsLean/KernelProgram.lean"
    "src/systems/SystemsLean/ParityProgram.lean"
    "src/systems/SystemsLean/KernelEmit.lean"
    "src/systems/SystemsLean/ParityEmit.lean"
    "src/systems/SystemsLean/SelfApply.lean"
    "src/systems/SystemsLean/SelfApplyFs.lean"
    "src/systems/SystemsLean/LlvmHold.lean"
    "src/systems/SystemsLean/InventoryClose.lean"
    "src/systems/SystemsLean/ProductPath.lean"
    "src/systems/SystemsLean/DualResidual.lean"
    "src/systems/SystemsLean/ProbeWire.lean"
    "src/systems/SystemsLean/SpecProof.lean"
    "src/systems/SystemsLean/SelfHostBody.lean"
  ];

  # Unit-surface docs + .slake honesty (former check.sh need[] greps).
  # types.md: COMMON-UNIVERSE only; HOST-RESIDUAL / PRODUCT-WIRE-RESIDUAL
  # stay on Types.slake + SystemsLean/Types.lean.
  unitSurfaceSpecs = [
    {
      rel = "src/systems/types.md";
      all = [
        "COMMON-UNIVERSE"
        "FAIL-CLOSED-UNKNOWN-KIND"
        "TYPES-THEOREM"
        "HOST-TYPES-THEOREM"
        "ofKindTag?_fail_closed"
        "kindMultOk"
        "mkNode?_mismatch_none"
        "mkNode?_ok"
        "expectedMult_value"
        "isWellTyped_eq_kindMultOk"
        "IR-PROGRAM-THEOREM"
        "HOST-IR-PROGRAM-THEOREM"
        "isWellTyped_empty_false"
        "isWellTyped_single_value"
        "foldWellTyped_single_value_some"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "IR-GRAPH-THEOREM"
        "HOST-IR-GRAPH-THEOREM"
        "EMPTY-GRAPH-OK"
        "edgesSound_empty"
        "HOST-PARITY-TYPES"
        "SELF-HOST-PARITY-TYPES"
        "HOST-PARITY-PROGRAM"
        "SELF-HOST-PARITY-PROGRAM"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
      ];
    }
    {
      rel = "src/systems/mult.md";
      all = [
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT-THEOREM"
        "HOST-MULT-THEOREM"
        "ofNat?_fail_closed"
        "name_mult0"
        "ofNat?_some_implies_isValidTag"
        "ofNat?_name_zero"
        "ofNat?_name_fail_closed"
      ];
    }
    {
      rel = "src/systems/Mult.slake";
      all = [ "FAIL-CLOSED-UNKNOWN-GRADE" ];
    }
    {
      rel = "src/systems/linear.md";
      all = [
        "LINEAR-EXACT-ONCE"
        "SELF-HOST-KERNEL-LINEAR"
        "HOST-KERNEL-LINEAR"
        "HOST-PARITY-LINEAR"
        "SELF-HOST-PARITY-LINEAR"
        "LINEAR-THEOREM"
        "HOST-LINEAR-THEOREM"
        "shareNat_eq"
        "shareNat_zero"
        "shareNat_succ"
        "JOIN-ALG"
      ];
    }
    {
      rel = "src/systems/Linear.slake";
      all = [
        "LINEAR-EXACT-ONCE"
        "JOIN-ALG"
        "ConsumeToken"
      ];
    }
    {
      rel = "src/systems/erasure.md";
      all = [ "ERASE-RULE-MULT-0" ];
    }
    {
      rel = "src/systems/Erasure.slake";
      all = [
        "ERASE-RULE-MULT-0"
        "EDGE-PROP"
        "ERASE-PROP"
      ];
    }
    {
      rel = "src/systems/Extract.slake";
      all = [
        "RUNTIME-FS"
        "EDGE-RUNTIME"
        "RUNTIME-CLASSIC"
        "EMIT-BOUNDARY"
      ];
    }
    {
      rel = "src/systems/extract.md";
      all = [
        "EMIT-BOUNDARY"
        "COMPOSE-THEOREM"
        "HOST-COMPOSE-THEOREM"
        "multPreScan_empty_true"
        "mint_zero_badId"
        "markErased_idempotent"
        "multPreScan_omega_only_true"
        "mint_consume_roundtrip"
      ];
    }
    {
      # Host PARTIAL inventory Mult..SelfHostBody (greppable miss list / empty).
      rel = "src/systems/host-partial-inventory.md";
      all = [
        "HOST-PARTIAL-INVENTORY"
        "SYSTEMS_LEAN_HOST"
        "CLOSABLE-MISS-COUNT-0"
        "intentional PARTIAL"
        "Mult..LlvmHold"
        "Mult..InventoryClose"
        "Mult..ProductPath"
        "Mult..DualResidual"
        "Mult..ProbeWire"
        "Mult..SpecProof"
        "Mult..SelfHostBody"
        "HOST-INVENTORY-CLOSE"
        "SELF-HOST-INVENTORY-CLOSE"
        "HOST-PRODUCT-PATH"
        "SELF-HOST-PRODUCT-PATH"
        "HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST-PRODUCT-PATH-CLOSE"
        "HOST-DUAL-RESIDUAL"
        "SELF-HOST-DUAL-RESIDUAL"
        "HOST-PROBE-WIRE"
        "SELF-HOST-PROBE-WIRE"
        "HOST-SPEC-PROOF"
        "SELF-HOST-SPEC-PROOF"
        "HOST-SELF-HOST-BODY"
        "SELF-HOST-BODY"
        "SELF-HOST-KERNEL-MULT"
        "HOST-EMIT-MULT"
        "HOST-PARITY-MULT"
        "SELF-HOST-KERNEL-LINEAR"
        "HOST-KERNEL-LINEAR"
        "HOST-PARITY-LINEAR"
        "SELF-HOST-PARITY-LINEAR"
        "SELF-HOST-KERNEL-TYPES"
        "HOST-KERNEL-TYPES"
        "HOST-PARITY-TYPES"
        "SELF-HOST-PARITY-TYPES"
        "SELF-HOST-KERNEL-PROGRAM"
        "HOST-KERNEL-PROGRAM"
        "HOST-PARITY-PROGRAM"
        "SELF-HOST-PARITY-PROGRAM"
        "SELF-HOST-KERNEL-EMIT"
        "HOST-KERNEL-EMIT"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "HOST-SELF-APPLY"
        "SELF-HOST-SELF-APPLY"
        "HOST-SELF-APPLY-FS"
        "SELF-HOST-SELF-APPLY-FS"
        "HOST-LLVM-HOLD"
        "SELF-HOST-LLVM-HOLD"
        "HOST-PROVABLY-HOLD"
      ];
    }
    {
      # SURFACE-MATRIX inventory prose (P7 progressive superset surface).
      rel = "src/systems/surface-matrix.md";
      all = [
        "SURFACE-MATRIX"
        "SLAKE_SURFACE_MATRIX_V0"
        "HOST-SURFACE-MATRIX"
        "present-partial"
        "open"
        "SYSTEMS_LEAN_HOST"
        "ConsumeToken"
        "ErasedIndex"
        "UnrestrictedShare"
      ];
    }
    {
      rel = "src/systems/Types.slake";
      all = [
        "COMMON-UNIVERSE"
        "HOST-RESIDUAL"
        "PRODUCT-WIRE-RESIDUAL"
      ];
    }
  ];

  # SYSTEMS_LEAN_HOST modules: marker + namespaces + smoke helpers.
  hostSpecs = [
    {
      rel = "src/systems/SystemsLean/Mult.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT-THEOREM"
        "HOST-MULT-THEOREM"
        "ofNat?_fail_closed"
        "isValidTag_fail_closed"
        "ofNat?_zero"
        "ofNat?_one"
        "ofNat?_two"
        "isValid_true"
        "isValidTag_eq_ofNat?_isSome"
        "name_mult0"
        "name_mult1"
        "name_multOmega"
        "ofNat?_some_implies_isValidTag"
        "ofNat?_name_zero"
        "ofNat?_name_one"
        "ofNat?_name_two"
        "ofNat?_name_fail_closed"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem ofNat?_fail_closed"
        "theorem isValidTag_fail_closed"
        "theorem name_mult0"
        "theorem ofNat?_some_implies_isValidTag"
        "theorem ofNat?_name_zero"
        "theorem ofNat?_name_one"
        "theorem ofNat?_name_two"
        "theorem ofNat?_name_fail_closed"
        "SystemsLean.Mult"
      ];
      anyGroups = [
        [
          "isValid"
          "multIsValid"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/Linear.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "JOIN-ALG"
        "ConsumeToken"
        "MULT-1"
        "LINEAR-EXACT-ONCE"
        "LINEAR-THEOREM"
        "HOST-LINEAR-THEOREM"
        "shareNat_eq"
        "shareNat_zero"
        "shareNat_succ"
        "polyId_id"
        "roundTrip_eq"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem shareNat_eq"
        "theorem shareNat_zero"
        "theorem shareNat_succ"
        "theorem polyId_id"
        "theorem roundTrip_eq"
        "SystemsLean.Linear"
      ];
    }
    {
      rel = "src/systems/SystemsLean/Types.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "COMMON-UNIVERSE"
        "HOST-RESIDUAL"
        "PRODUCT-WIRE-RESIDUAL"
        "FAIL-CLOSED-UNKNOWN-KIND"
        "TYPES-THEOREM"
        "HOST-TYPES-THEOREM"
        "ofKindTag?_fail_closed"
        "isValidKindTag_fail_closed"
        "ofKindTag?_zero"
        "ofKindTag?_one"
        "ofKindTag?_two"
        "isValidKindTag_eq_ofKindTag?_isSome"
        "isValidKindTag_zero"
        "isValidKindTag_one"
        "isValidKindTag_two"
        "kindMultOk_value_omega"
        "kindMultOk_linear_one"
        "kindMultOk_erased_zero"
        "kindMultOk_value_not_one"
        "kindMultOk_value_not_zero"
        "kindMultOk_linear_not_omega"
        "kindMultOk_linear_not_zero"
        "kindMultOk_erased_not_omega"
        "kindMultOk_erased_not_one"
        "mkNode?_mismatch_none"
        "expectedMult_value"
        "expectedMult_linear"
        "expectedMult_erased"
        "isWellTyped_eq_kindMultOk"
        "mkNode?_ok"
        "mkNodeFromTags?_unknown_mult"
        "mkNodeFromTags?_unknown_kind"
        "mkNodeFromTags?_value_omega_some"
        "mkNodeFromTags?_linear_one_some"
        "mkNodeFromTags?_erased_zero_some"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem ofKindTag?_fail_closed"
        "theorem isValidKindTag_fail_closed"
        "theorem kindMultOk_value_not_one"
        "theorem mkNode?_mismatch_none"
        "theorem mkNode?_ok"
        "theorem expectedMult_value"
        "theorem isWellTyped_eq_kindMultOk"
        "theorem mkNodeFromTags?_unknown_mult"
        "SystemsLean.Types"
      ];
      anyGroups = [
        [
          "kindMultOk"
          "isWellTyped"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/IrProgram.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "ORDERED-IR-PROGRAM"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "IR-PROGRAM-THEOREM"
        "HOST-IR-PROGRAM-THEOREM"
        "isWellTyped_empty_false"
        "empty_not_well_typed"
        "empty_isEmpty"
        "empty_length_zero"
        "checkFailClosed_eq_isWellTyped"
        "foldWellTyped_empty_none"
        "foldWellTyped_ill_typed_none"
        "push_bad_node"
        "programCap_eq_eight"
        "push_value_one_ok"
        "length_single_value"
        "isWellTyped_single_value"
        "foldWellTyped_single_value_some"
        "isWellTyped_two_values"
        "length_two_values"
        "foldWellTyped_two_values_some"
        "push_second_value_ok"
        "push_full_at_cap"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem isWellTyped_empty_false"
        "theorem empty_not_well_typed"
        "theorem foldWellTyped_ill_typed_none"
        "theorem push_bad_node"
        "theorem push_value_one_ok"
        "theorem isWellTyped_single_value"
        "theorem foldWellTyped_single_value_some"
        "theorem isWellTyped_two_values"
        "theorem length_two_values"
        "theorem foldWellTyped_two_values_some"
        "theorem push_second_value_ok"
        "theorem push_full_at_cap"
        "SystemsLean.IrProgram"
      ];
      anyGroups = [
        [
          "push"
          "foldWellTyped"
          "isWellTyped"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/Erasure.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "ERASE-RULE-MULT-0"
        "ERASE-NO-RUNTIME"
        "EDGE-PROP"
        "ERASE-PROP"
        "SystemsLean.Erasure"
        "ERASURE-THEOREM"
        "HOST-ERASURE-THEOREM"
        "isRuntimeAbsent_unmarked_false"
        "markForGrade?_mult1_none"
        "checkFailClosed_unmarked_false"
        "checkFailClosed_eq"
        "markForGrade?_some_implies_isErasureGrade"
        "markForGrade?_some_is_mark"
        "isRuntimeAbsent_eq_marked"
        "markForGrade?_mult0_isRuntimeAbsent"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem isRuntimeAbsent_unmarked_false"
        "theorem markForGrade?_mult1_none"
        "theorem checkFailClosed_unmarked_false"
        "theorem checkFailClosed_eq"
        "theorem markForGrade?_some_implies_isErasureGrade"
        "theorem markForGrade?_some_is_mark"
        "theorem isRuntimeAbsent_eq_marked"
        "theorem markForGrade?_mult0_isRuntimeAbsent"
      ];
      anyGroups = [
        [
          "isRuntimeAbsent"
          "mark"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/Extract.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "EMIT-BOUNDARY"
        "RUNTIME-FS"
        "EDGE-RUNTIME"
        "RUNTIME-CLASSIC"
        "SystemsLean.Extract"
        "EXTRACT-THEOREM"
        "HOST-EXTRACT-THEOREM"
        "isFreestandingGoal_runtimeFs"
        "extractOk_classic_reject"
        "ofRuntimeTag?_fail_closed"
        "ofRuntimeTag?_some_implies_isValidRuntimeTag"
        "isValidRuntimeTag_zero"
        "isValidRuntimeTag_one"
        "isValidRuntimeTag_two"
        "extractOkFromTags?_mult1_fs_true"
        "extractOkFromTags?_omega_fs_true"
        "extractOkFromTags?_mult0_marked_fs_true"
        "extractOkFromTags?_mult0_unmarked_fs_false"
        "extractOkFromTags?_classic_reject"
        "extractOkFromTags?_edge_reject"
        "extractOkFromTags?_both_unknown_none"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem isFreestandingGoal_runtimeFs"
        "theorem extractOk_classic_reject"
        "theorem ofRuntimeTag?_fail_closed"
        "theorem ofRuntimeTag?_some_implies_isValidRuntimeTag"
        "theorem isValidRuntimeTag_zero"
        "theorem isValidRuntimeTag_one"
        "theorem isValidRuntimeTag_two"
        "theorem extractOkFromTags?_mult1_fs_true"
        "theorem extractOkFromTags?_omega_fs_true"
        "theorem extractOkFromTags?_mult0_marked_fs_true"
        "theorem extractOkFromTags?_mult0_unmarked_fs_false"
        "theorem extractOkFromTags?_classic_reject"
        "theorem extractOkFromTags?_edge_reject"
        "theorem extractOkFromTags?_both_unknown_none"
      ];
      anyGroups = [
        [
          "extractOk"
          "checkFailClosed"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/IrGraph.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "IR_GRAPH_EDGES_V0"
        "IR-GRAPH-EDGES"
        "EMPTY-GRAPH-OK"
        "SLAKE_IR_EDGE_MAX"
        "IR-GRAPH-SMOKE"
        "example"
        "edgesSound"
        "IR-GRAPH-THEOREM"
        "HOST-IR-GRAPH-THEOREM"
        "isWellTyped_empty_true"
        "empty_well_typed"
        "checkFailClosed_eq_isWellTyped"
        "empty_isEmpty"
        "edgeMax_eq_sixteen"
        "addEdge_empty_badEndpoints"
        "edgesSound_empty"
        "isWellTyped_one_node_empty_edges"
        "pushNode_value_one_ok"
        "addEdge_one_node_self_ok"
        "addEdge_one_node_badEndpoints"
        "edgesSound_one_edge"
        "isWellTyped_two_nodes_one_edge"
        "addEdge_two_nodes_ok"
        "edgesSound_two_edges"
        "isWellTyped_two_nodes_two_edges"
        "addEdge_two_nodes_second_ok"
        "addEdge_two_nodes_badEndpoints"
        "edgesSound_oversize_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem isWellTyped_empty_true"
        "theorem empty_well_typed"
        "theorem addEdge_empty_badEndpoints"
        "theorem edgesSound_empty"
        "theorem isWellTyped_one_node_empty_edges"
        "theorem pushNode_value_one_ok"
        "theorem addEdge_one_node_self_ok"
        "theorem addEdge_one_node_badEndpoints"
        "theorem edgesSound_one_edge"
        "theorem isWellTyped_two_nodes_one_edge"
        "theorem addEdge_two_nodes_ok"
        "theorem edgesSound_two_edges"
        "theorem isWellTyped_two_nodes_two_edges"
        "theorem addEdge_two_nodes_second_ok"
        "theorem addEdge_two_nodes_badEndpoints"
        "theorem edgesSound_oversize_false"
        "SystemsLean.IrGraph"
      ];
      anyGroups = [
        [
          "addEdge"
          "pushNode"
          "isWellTyped"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/HostCompose.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "HOST_COMPOSE_V0"
        "HOST-COMPOSE"
        "EMIT-BOUNDARY"
        "RUNTIME-FS"
        "HOST-SMOKE"
        "example"
        "SystemsLean.HostCompose"
        "COMPOSE-THEOREM"
        "HOST-COMPOSE-THEOREM"
        "multPreScan_empty_true"
        "mint_zero_badId"
        "consume_empty_notLive"
        "nodeMultOk_mult1_eq_live"
        "double_consume_notLive"
        "checkFailClosed_eq"
        "multPreScan_mult1_unminted_false"
        "extractOkFs_mult1_unminted_false"
        "multPreScan_mult1_minted_true"
        "extractOkFs_mult1_minted_true"
        "multPreScan_mult0_unmarked_false"
        "multPreScan_mult0_marked_true"
        "markErased_idempotent"
        "multPreScan_omega_only_true"
        "extractOkFs_omega_only_true"
        "consume_live_payload"
        "mint_nonzero_ok"
        "mint_consume_roundtrip"
        "pushHostNode_bad_node"
        "pushHostNode_value_one_ok"
        "addHostEdge_empty_badEndpoints"
        "addHostEdge_two_values_ok"
        "addHostEdge_one_node_badEndpoints"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem multPreScan_empty_true"
        "theorem mint_zero_badId"
        "theorem consume_empty_notLive"
        "theorem nodeMultOk_mult1_eq_live"
        "theorem double_consume_notLive"
        "theorem checkFailClosed_eq"
        "theorem multPreScan_mult1_unminted_false"
        "theorem extractOkFs_mult1_unminted_false"
        "theorem multPreScan_mult1_minted_true"
        "theorem markErased_idempotent"
        "theorem multPreScan_omega_only_true"
        "theorem mint_consume_roundtrip"
        "theorem pushHostNode_bad_node"
        "theorem pushHostNode_value_one_ok"
        "theorem addHostEdge_empty_badEndpoints"
        "theorem addHostEdge_two_values_ok"
        "theorem addHostEdge_one_node_badEndpoints"
      ];
      anyGroups = [
        [
          "extractOk"
          "checkFailClosed"
        ]
        [
          "JOIN-ALG"
          "ConsumeToken"
        ]
        [
          "mint"
          "consume"
          "markErased"
        ]
        [
          "pushHostNode"
          "addHostEdge"
          "hostIsWellTyped"
        ]
        [
          "multPreScan"
          "nodeMultOk"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/EmitPlan.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "EMIT_PLAN_V0"
        "EMIT-PLAN"
        "planFromCompose"
        "isReady"
        "checkFailClosed"
        "SystemsLean.EmitPlan"
        "EMIT-PLAN-SMOKE"
        "example"
        "EMIT-PLAN-THEOREM"
        "HOST-EMIT-PLAN-THEOREM"
        "planOk_empty_true"
        "planFromCompose_empty_counts_zero"
        "isReady_empty_plan"
        "planOk_mult1_unminted_false"
        "planOk_mult1_minted_true"
        "planFromCompose_two_values_edge"
        "planFromCompose_linear_and_erased"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem planOk_empty_true"
        "theorem planFromCompose_empty_counts_zero"
        "theorem isReady_empty_plan"
        "theorem planOk_mult1_unminted_false"
        "theorem planOk_mult1_minted_true"
        "theorem planFromCompose_two_values_edge"
        "theorem planFromCompose_linear_and_erased"
      ];
    }
    {
      rel = "src/systems/SystemsLean/EmitApply.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "EMIT_APPLY_V0"
        "EMIT-APPLY"
        "applyFromCompose"
        "applyIsValid"
        "checkFailClosed"
        "SystemsLean.EmitApply"
        "applyCap"
        "packTag"
        "EMIT-APPLY-SMOKE"
        "example"
        "EMIT-APPLY-THEOREM"
        "HOST-EMIT-APPLY-THEOREM"
        "applyCap_eq_32"
        "applyOk_empty_true"
        "applyOk_linear_without_mint_false"
        "packTag_linear"
        "applyFromCompose_mult1_minted_tags"
        "applyFromCompose_linear_and_erased_order"
        "applyIsValid_count_tags_desync_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem applyCap_eq_32"
        "theorem applyOk_empty_true"
        "theorem applyOk_linear_without_mint_false"
        "theorem packTag_linear"
        "theorem applyFromCompose_mult1_minted_tags"
        "theorem applyFromCompose_linear_and_erased_order"
        "theorem applyIsValid_count_tags_desync_false"
      ];
      anyGroups = [
        [
          "APPLY_CAP"
          "SLAKE_EMIT_APPLY_CAP"
        ]
      ];
    }
    {
      rel = "src/systems/SystemsLean/EmitBody.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "EMIT_BODY_V0"
        "EMIT-BODY"
        "bodyFromCompose"
        "bodyIsValid"
        "buildFragment"
        "SystemsLean.EmitBody"
        "bodyCap"
        "EMIT-BODY-SMOKE"
        "example"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "HOST-EMIT-SSOT"
        "emptyComposeFragmentSsot"
        "/* EMIT_BODY_V0 RUNTIME-FS r=0 e=0 */"
        "EMIT-BODY-THEOREM"
        "HOST-EMIT-BODY-THEOREM"
        "bodyCap_eq_256"
        "emptyComposeFragmentSsot_eq"
        "bodyOk_empty_true"
        "bodyOk_mult1_unminted_false"
        "bodyOk_mult1_minted_true"
        "bodyFromCompose_mult1_minted_buf"
        "bodyFromCompose_mult0_marked_buf"
        "bodyOk_omega_true"
        "bodyFromCompose_linear_and_erased"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem bodyCap_eq_256"
        "theorem emptyComposeFragmentSsot_eq"
        "theorem bodyOk_empty_true"
        "theorem bodyOk_mult1_unminted_false"
        "theorem bodyOk_mult1_minted_true"
        "theorem bodyFromCompose_mult1_minted_buf"
        "theorem bodyFromCompose_mult0_marked_buf"
        "theorem bodyOk_omega_true"
        "theorem bodyFromCompose_linear_and_erased"
      ];
      anyGroups = [
        [
          "BODY_CAP"
          "SLAKE_EMIT_BODY_CAP"
        ]
      ];
    }
    {
      # HOST-COMPILE-PATH (P3): host-informed compile-path readiness (V1).
      rel = "src/systems/SystemsLean/CompilePath.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_COMPILE_PATH_V1"
        "HOST-COMPILE-PATH"
        "COMPILE-PATH"
        "compileReady"
        "unitCompileReady"
        "programCompileReady"
        "gradeSurfaceOk"
        "SystemsLean.CompilePath"
        "COMPILE-PATH-SMOKE"
        "example"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-COMPOSE"
        "COMPILE-PATH-THEOREM"
        "HOST-COMPILE-PATH-THEOREM"
        "compileReady_empty_true"
        "unitCompileReady_empty_true"
        "programCompileReady_empty_false"
        "programCompileReady_eq_isWellTyped"
        "gradeSurfaceOk_true"
        "empty_host_ok_ne_empty_program_ok"
        "stageId_eq"
        "hostCompilePathId_eq"
        "extractFsOk_eq"
        "compileReady_eq_extractFsOk"
        "unitCompileReady_eq"
        "extractClaimOk_classic_empty_false"
        "extractClaimOk_edge_empty_false"
        "extractClaimOk_fs_empty_true"
        "verdictOf_empty_ok"
        "programCompileReady_single_value"
        "compileReady_mult1_unminted_false"
        "unitCompileReady_mult1_minted_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem compileReady_empty_true"
        "theorem programCompileReady_empty_false"
        "theorem empty_host_ok_ne_empty_program_ok"
        "theorem stageId_eq"
        "theorem hostCompilePathId_eq"
        "theorem extractFsOk_eq"
        "theorem compileReady_eq_extractFsOk"
        "theorem unitCompileReady_eq"
        "theorem extractClaimOk_classic_empty_false"
        "theorem extractClaimOk_edge_empty_false"
        "theorem extractClaimOk_fs_empty_true"
        "theorem verdictOf_empty_ok"
        "theorem programCompileReady_single_value"
        "theorem compileReady_mult1_unminted_false"
        "theorem unitCompileReady_mult1_minted_true"
      ];
      anyGroups = [
        [
          "verdictOf"
          "checkHost"
        ]
      ];
    }
    {
      # HOST-JOIN-MAP (P4): dual / JOIN honesty into compile-path readiness.
      # JOIN-ALG-USE: host use pins (not dual-path cite alone) for three duals.
      rel = "src/systems/SystemsLean/JoinMap.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_JOIN_MAP_V0"
        "HOST-JOIN-MAP"
        "JOIN-MAP"
        "JOIN-ALG"
        "JOIN-ALG-USE"
        "ConsumeToken"
        "ErasedIndex"
        "UnrestrictedShare"
        "joinAlgContractOk"
        "joinAlgUseOk"
        "joinDualCiteOk"
        "consumeTokenHostUseOk"
        "erasedIndexHostUseOk"
        "unrestrictedShareHostUseOk"
        "joinUnitCompileReady"
        "joinProgramCompileReady"
        "joinCompileReady"
        "SystemsLean.JoinMap"
        "JOIN-MAP-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-COMPILE-PATH"
        "LINEAR-EXACT-ONCE"
        "MULT-OMEGA"
        "src/idris2/examples/ConsumeToken.idr"
        "src/lean4/examples/ConsumeToken.lean"
        "src/idris2/examples/ErasedIndex.idr"
        "src/lean4/examples/ErasedIndex.lean"
        "src/idris2/examples/UnrestrictedShare.idr"
        "src/lean4/examples/UnrestrictedShare.lean"
        "JOIN-MAP-THEOREM"
        "HOST-JOIN-MAP-THEOREM"
        "joinUnitCompileReady_empty_true"
        "joinProgramCompileReady_empty_false"
        "joinAlgContractOk_true"
        "joinAlgUseOk_true"
        "joinUnitCompileReady_eq"
        "joinProgramCompileReady_eq"
        "joinUnitCompileReady_mult1_unminted_false"
        "joinUnitCompileReady_mult1_minted_true"
        "joinProgramCompileReady_single_value"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem joinUnitCompileReady_empty_true"
        "theorem joinProgramCompileReady_empty_false"
        "theorem joinAlgContractOk_true"
        "theorem joinAlgUseOk_true"
        "theorem joinUnitCompileReady_eq"
        "theorem joinProgramCompileReady_eq"
        "theorem joinUnitCompileReady_mult1_unminted_false"
        "theorem joinUnitCompileReady_mult1_minted_true"
        "theorem joinProgramCompileReady_single_value"
      ];
      anyGroups = [
        [
          "verdictOf"
          "joinLinearCiteOk"
        ]
      ];
    }
    {
      # HOST-SELF-HOST (P5): self-host direction readiness from join map + surface.
      rel = "src/systems/SystemsLean/SelfHost.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_V0"
        "HOST-SELF-HOST"
        "SELF-HOST"
        "hostSurfaceOk"
        "selfHostUnitReady"
        "selfHostProgramReady"
        "selfHostReady"
        "SystemsLean.SelfHost"
        "SELF-HOST-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-JOIN-MAP"
        "SLAKE_JOIN_MAP_V0"
        "HOST-COMPILE-PATH"
        "SLAKE_COMPILE_PATH_V1"
        "src/systems/SystemsLean.lean"
        "src/systems/SystemsLean/SelfHost.lean"
        "SELF-HOST-THEOREM"
        "HOST-SELF-HOST-THEOREM"
        "selfHostUnitReady_empty_true"
        "selfHostProgramReady_empty_false"
        "hostSurfaceOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem selfHostUnitReady_empty_true"
        "theorem selfHostProgramReady_empty_false"
        "theorem hostSurfaceOk_true"
      ];
      anyGroups = [
        [
          "verdictOf"
          "packageRootPath"
        ]
      ];
    }
    {
      # HOST-SURFACE-MATRIX (P7): progressive superset surface inventory + gate.
      rel = "src/systems/SystemsLean/SurfaceMatrix.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SURFACE_MATRIX_V0"
        "HOST-SURFACE-MATRIX"
        "SURFACE-MATRIX"
        "matrixSurfaceOk"
        "matrixUnitReady"
        "matrixProgramReady"
        "matrixReady"
        "SystemsLean.SurfaceMatrix"
        "SURFACE-MATRIX-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED"
        "HOST-SELF-HOST"
        "SLAKE_SELF_HOST_V0"
        "HOST-JOIN-MAP"
        "HOST-COMPILE-PATH"
        "present-partial"
        "open"
        "ConsumeToken"
        "ErasedIndex"
        "UnrestrictedShare"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "src/idris2/examples/ConsumeToken.idr"
        "src/lean4/examples/ConsumeToken.lean"
        "src/idris2/examples/ErasedIndex.idr"
        "src/lean4/examples/ErasedIndex.lean"
        "src/idris2/examples/UnrestrictedShare.idr"
        "src/lean4/examples/UnrestrictedShare.lean"
        "src/systems/surface-matrix.md"
        "src/systems/SystemsLean/SurfaceMatrix.lean"
        "SURFACE-MATRIX-THEOREM"
        "HOST-SURFACE-MATRIX-THEOREM"
        "matrixUnitReady_empty_true"
        "matrixProgramReady_empty_false"
        "matrixSurfaceOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem matrixUnitReady_empty_true"
        "theorem matrixProgramReady_empty_false"
        "theorem matrixSurfaceOk_true"
      ];
      anyGroups = [
        [
          "verdictOf"
          "dualCiteOk"
        ]
      ];
    }
    {
      # SELF-HOST acceptance prose (SH0..SH5 partial + SH5 freestanding deepen + SH6 hold).
      rel = "src/systems/self-host.md";
      all = [
        "SELF-HOST"
        "SELF-HOST-ACCEPTANCE"
        "SLAKE_SELF_HOST_KERNEL_MULT_V0"
        "SELF-HOST-KERNEL-MULT"
        "SLAKE_SELF_HOST_EMIT_MULT_V0"
        "HOST-EMIT-MULT"
        "SLAKE_SELF_HOST_PARITY_MULT_V0"
        "HOST-PARITY-MULT"
        "SELF-HOST-PARITY-MULT"
        "SLAKE_SELF_HOST_KERNEL_LINEAR_V0"
        "SELF-HOST-KERNEL-LINEAR"
        "HOST-KERNEL-LINEAR"
        "SLAKE_SELF_HOST_PARITY_LINEAR_V0"
        "HOST-PARITY-LINEAR"
        "SELF-HOST-PARITY-LINEAR"
        "SLAKE_SELF_HOST_KERNEL_TYPES_V0"
        "SELF-HOST-KERNEL-TYPES"
        "HOST-KERNEL-TYPES"
        "SLAKE_SELF_HOST_PARITY_TYPES_V0"
        "HOST-PARITY-TYPES"
        "SELF-HOST-PARITY-TYPES"
        "SLAKE_SELF_HOST_KERNEL_PROGRAM_V0"
        "SELF-HOST-KERNEL-PROGRAM"
        "HOST-KERNEL-PROGRAM"
        "SLAKE_SELF_HOST_PARITY_PROGRAM_V0"
        "HOST-PARITY-PROGRAM"
        "SELF-HOST-PARITY-PROGRAM"
        "SLAKE_SELF_HOST_KERNEL_EMIT_V0"
        "SELF-HOST-KERNEL-EMIT"
        "HOST-KERNEL-EMIT"
        "SLAKE_SELF_HOST_PARITY_EMIT_V0"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "SLAKE_SELF_HOST_SELF_APPLY_V0"
        "HOST-SELF-APPLY"
        "SELF-HOST-SELF-APPLY"
        "SLAKE_SELF_HOST_SELF_APPLY_FS_V0"
        "HOST-SELF-APPLY-FS"
        "SELF-HOST-SELF-APPLY-FS"
        "SLAKE_SELF_HOST_LLVM_HOLD_V0"
        "HOST-LLVM-HOLD"
        "SELF-HOST-LLVM-HOLD"
        "HOST-PROVABLY-HOLD"
        "SLAKE_SELF_HOST_INVENTORY_CLOSE_V0"
        "HOST-INVENTORY-CLOSE"
        "SELF-HOST-INVENTORY-CLOSE"
        "SLAKE_SELF_HOST_PRODUCT_PATH_V0"
        "HOST-PRODUCT-PATH"
        "SELF-HOST-PRODUCT-PATH"
        "SLAKE_SELF_HOST_PRODUCT_PATH_CLOSE_V0"
        "HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST-PRODUCT-PATH-CLOSE"
        "productPathCloseReady"
        "productPathLadderClosedOk"
        "SLAKE_SELF_HOST_DUAL_RESIDUAL_V0"
        "HOST-DUAL-RESIDUAL"
        "SELF-HOST-DUAL-RESIDUAL"
        "dualResidualReady"
        "hostElaboratorResidualRemains"
        "productResidualRemains"
        "SLAKE_SELF_HOST_PROBE_WIRE_V0"
        "HOST-PROBE-WIRE"
        "SELF-HOST-PROBE-WIRE"
        "probeWireReady"
        "behavioralProbeIsSmokeDebt"
        "product freestanding wire"
        "SLAKE_SELF_HOST_SPEC_PROOF_V0"
        "HOST-SPEC-PROOF"
        "SELF-HOST-SPEC-PROOF"
        "specProofReady"
        "specSurfaceStated"
        "proofCompleteClaimed"
        "proofs do not retire tests"
        "SLAKE_SELF_HOST_BODY_V0"
        "HOST-SELF-HOST-BODY"
        "SELF-HOST-BODY"
        "selfHostBodyReady"
        "defined freestanding compile step"
        "SLAKE_EMIT_FREESTANDING_C_V0"
        "product wire"
        "Host model"
        "not residual free"
        "Not PROVABLY"
      ];
    }
    {
      # Mult self-host kernel IR fixture (SH1 start).
      rel = "src/systems/SystemsLean/KernelMult.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_MULT_V0"
        "SELF-HOST-KERNEL-MULT"
        "SELF-HOST"
        "lowerMultKernel"
        "multKernelProgram"
        "multKernelReady"
        "kernelOk"
        "SystemsLean.KernelMult"
        "KERNEL-MULT-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "ORDERED-IR-PROGRAM"
        "HOST-COMPILE-PATH"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/KernelMult.lean"
        "KERNEL-MULT-THEOREM"
        "HOST-KERNEL-MULT-THEOREM"
        "multKernelReady_true"
        "kernelOk_true"
        "programCompileReady_empty_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem multKernelReady_true"
        "theorem kernelOk_true"
        "theorem programCompileReady_empty_false"
      ];
      anyGroups = [
        [
          "unknownTagRejected"
          "kernelSurfaceOk"
        ]
      ];
    }
    {
      # Host-owned Mult freestanding product emit (SH2).
      rel = "src/systems/SystemsLean/EmitMult.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_EMIT_MULT_V0"
        "HOST-EMIT-MULT"
        "SELF-HOST-EMIT-MULT"
        "multHeaderFragment"
        "multBodyFragment"
        "emitMultReady"
        "SystemsLean.EmitMult"
        "EMIT-MULT-SMOKE"
        "HOST-EMIT-MULT-SMOKE"
        "example"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_mult_is_valid"
        "NON-SSOT"
        "src/systems/emit/host_emit_mult.ssot.txt"
        "src/systems/SystemsLean/EmitMult.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
      ];
      anyGroups = [
        [
          "emitMultOk"
          "headerHonestyOk"
        ]
      ];
    }
    {
      # Host-owned Linear freestanding product emit (HOST-EMIT-LINEAR).
      rel = "src/systems/SystemsLean/EmitLinear.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_EMIT_LINEAR_V0"
        "HOST-EMIT-LINEAR"
        "SELF-HOST-EMIT-LINEAR"
        "linearHeaderFragment"
        "linearBodyFragment"
        "emitLinearReady"
        "SystemsLean.EmitLinear"
        "EMIT-LINEAR-SMOKE"
        "HOST-EMIT-LINEAR-SMOKE"
        "example"
        "LINEAR-EXACT-ONCE"
        "CONSUME_TOKEN_HOST_V0"
        "JOIN-ALG"
        "slake_linear_consume"
        "slake_consume_token_consume"
        "NON-SSOT"
        "src/systems/emit/host_emit_linear.ssot.txt"
        "src/systems/SystemsLean/EmitLinear.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
      ];
      anyGroups = [
        [
          "emitLinearOk"
          "headerHonestyOk"
        ]
      ];
    }
    {
      # Mult closed-loop parity host + product contracts (SH3).
      rel = "src/systems/SystemsLean/ParityMult.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PARITY_MULT_V0"
        "HOST-PARITY-MULT"
        "SELF-HOST-PARITY-MULT"
        "multParityReady"
        "gradeParityOk"
        "SystemsLean.ParityMult"
        "PARITY-MULT-SMOKE"
        "HOST-PARITY-MULT-SMOKE"
        "example"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_mult_is_valid"
        "slake_mult_is_known"
        "slake_mult_name"
        "SELF-HOST-KERNEL-MULT"
        "HOST-EMIT-MULT"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/SystemsLean/ParityMult.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "PARITY-MULT-THEOREM"
        "HOST-PARITY-MULT-THEOREM"
        "multParityReady_true"
        "gradeParityOk_true"
        "multParityOk_eq_ready"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem multParityReady_true"
        "theorem gradeParityOk_true"
        "theorem ofNatRoundTripOk_true"
        "theorem multParityOk_eq_ready"
        # Content equality (parity table + product API; not pure readiness canaries).
        "ofNatRoundTrip_tag0"
        "ofNatRoundTrip_tag1"
        "ofNatRoundTrip_tagOmega"
        "ofNatRoundTrip_unknown3"
        "ofNatRoundTrip_unknown99"
        "isValidTag_tag0"
        "isValidTag_tag1"
        "isValidTag_tagOmega"
        "isValidTag_unknown3"
        "isValidTag_unknown99"
        "nameParity_mult0"
        "nameParity_mult1"
        "nameParity_multOmega"
        "enumTag_multC0"
        "enumTag_multC1"
        "enumTag_multCOmega"
        "productIsValidApi_eq"
        "productIsKnownApi_eq"
        "productNameApi_eq"
        "isValidParityOk_true"
        "enumTagParityOk_true"
        "theorem ofNatRoundTrip_tag0"
        "theorem ofNatRoundTrip_tag1"
        "theorem ofNatRoundTrip_tagOmega"
        "theorem ofNatRoundTrip_unknown3"
        "theorem ofNatRoundTrip_unknown99"
        "theorem isValidTag_tag0"
        "theorem isValidTag_tag1"
        "theorem isValidTag_tagOmega"
        "theorem isValidTag_unknown3"
        "theorem isValidTag_unknown99"
        "theorem nameParity_mult0"
        "theorem nameParity_mult1"
        "theorem nameParity_multOmega"
        "theorem enumTag_multC0"
        "theorem enumTag_multC1"
        "theorem enumTag_multCOmega"
        "theorem productIsValidApi_eq"
        "theorem productIsKnownApi_eq"
        "theorem productNameApi_eq"
        "theorem isValidParityOk_true"
        "theorem enumTagParityOk_true"
      ];
      anyGroups = [
        [
          "multParityOk"
          "paritySurfaceOk"
        ]
      ];
    }
    {
      # Linear self-host kernel IR + host compose path (SH4 start).
      rel = "src/systems/SystemsLean/KernelLinear.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_LINEAR_V0"
        "SELF-HOST-KERNEL-LINEAR"
        "HOST-KERNEL-LINEAR"
        "SELF-HOST"
        "lowerLinearKernel"
        "linearKernelProgram"
        "linearKernelReady"
        "linearHostPathReady"
        "linearKernelOk"
        "SystemsLean.KernelLinear"
        "KERNEL-LINEAR-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "LINEAR-EXACT-ONCE"
        "JOIN-ALG"
        "ConsumeToken"
        "MULT-1"
        "HOST-COMPOSE"
        "ORDERED-IR-PROGRAM"
        "HOST-COMPILE-PATH"
        "CONSUME_TOKEN_HOST_V0"
        "slake_linear_consume"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/KernelLinear.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "KERNEL-LINEAR-THEOREM"
        "HOST-KERNEL-LINEAR-THEOREM"
        "linearKernelReady_true"
        "linearKernelOk_true"
        "programCompileReady_empty_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem linearKernelReady_true"
        "theorem linearKernelOk_true"
        "theorem programCompileReady_empty_false"
      ];
      anyGroups = [
        [
          "linearSurfaceOk"
          "linearMismatchRejected"
        ]
      ];
    }
    {
      # Linear freestanding path parity host + product contracts (Mult+Linear deepen).
      rel = "src/systems/SystemsLean/ParityLinear.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PARITY_LINEAR_V0"
        "HOST-PARITY-LINEAR"
        "SELF-HOST-PARITY-LINEAR"
        "linearParityReady"
        "linearContractParityOk"
        "multLinearParityReady"
        "SystemsLean.ParityLinear"
        "PARITY-LINEAR-SMOKE"
        "HOST-PARITY-LINEAR-SMOKE"
        "example"
        "LINEAR-EXACT-ONCE"
        "JOIN-ALG"
        "ConsumeToken"
        "CONSUME_TOKEN_HOST_V0"
        "slake_linear_consume"
        "slake_linear_token_init"
        "slake_linear_token_is_live"
        "slake_linear_token_consume"
        "slake_consume_token_mint"
        "slake_consume_token_consume"
        "slake_consume_token_is_live"
        "HOST-KERNEL-LINEAR"
        "HOST-PARITY-MULT"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/SystemsLean/ParityLinear.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "PARITY-LINEAR-THEOREM"
        "HOST-PARITY-LINEAR-THEOREM"
        "linearParityReady_true"
        "linearContractParityOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem linearParityReady_true"
        "theorem linearContractParityOk_true"
        "theorem multLinearParityReady_true"
        # Content equality (product API surface; not pure readiness canaries).
        "productLinearConsumeApi_eq"
        "productLinearTokenInitApi_eq"
        "productLinearTokenIsLiveApi_eq"
        "productLinearTokenConsumeApi_eq"
        "productConsumeTokenMintApi_eq"
        "productConsumeTokenConsumeApi_eq"
        "productConsumeTokenIsLiveApi_eq"
        "productConsumeTokenHostId_eq"
        "productApiSurfaceOk_true"
        "theorem productLinearConsumeApi_eq"
        "theorem productLinearTokenInitApi_eq"
        "theorem productLinearTokenIsLiveApi_eq"
        "theorem productLinearTokenConsumeApi_eq"
        "theorem productConsumeTokenMintApi_eq"
        "theorem productConsumeTokenConsumeApi_eq"
        "theorem productConsumeTokenIsLiveApi_eq"
        "theorem productConsumeTokenHostId_eq"
        "theorem productApiSurfaceOk_true"
      ];
      anyGroups = [
        [
          "linearParityOk"
          "paritySurfaceOk"
          "productApiSurfaceOk"
        ]
      ];
    }
    {
      # Types self-host kernel IR + program path honesty (SH4 growth).
      rel = "src/systems/SystemsLean/KernelTypes.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_TYPES_V0"
        "SELF-HOST-KERNEL-TYPES"
        "HOST-KERNEL-TYPES"
        "SELF-HOST"
        "lowerTypesKernel"
        "typesKernelProgram"
        "typesKernelReady"
        "typesProgramPathReady"
        "typesKernelOk"
        "SystemsLean.KernelTypes"
        "KERNEL-TYPES-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "FAIL-CLOSED-UNKNOWN-KIND"
        "TYPED_IR_V0"
        "COMMON-UNIVERSE"
        "ORDERED-IR-PROGRAM"
        "HOST-COMPILE-PATH"
        "foldWellTyped"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_ir_node"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/KernelTypes.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "KERNEL-TYPES-THEOREM"
        "HOST-KERNEL-TYPES-THEOREM"
        "typesKernelReady_true"
        "typesKernelOk_true"
        "programCompileReady_empty_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem typesKernelReady_true"
        "theorem typesKernelOk_true"
        "theorem programCompileReady_empty_false"
      ];
      anyGroups = [
        [
          "typesSurfaceOk"
          "unknownKindRejected"
          "kindMultMismatchRejected"
        ]
      ];
    }
    {
      # Types freestanding path parity host + product contracts (Mult+Linear+Types).
      rel = "src/systems/SystemsLean/ParityTypes.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PARITY_TYPES_V0"
        "HOST-PARITY-TYPES"
        "SELF-HOST-PARITY-TYPES"
        "typesParityReady"
        "typesContractParityOk"
        "multLinearTypesParityReady"
        "SystemsLean.ParityTypes"
        "PARITY-TYPES-SMOKE"
        "HOST-PARITY-TYPES-SMOKE"
        "example"
        "TYPED_IR_V0"
        "slake_ir_node"
        "slake_ir_node_init"
        "slake_ir_node_is_well_typed"
        "slake_ir_node_check_fail_closed"
        "kindMultMismatchRejected"
        "typesProgramPathReady"
        "HOST-KERNEL-TYPES"
        "HOST-PARITY-LINEAR"
        "HOST-PARITY-MULT"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/SystemsLean/ParityTypes.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "PARITY-TYPES-THEOREM"
        "HOST-PARITY-TYPES-THEOREM"
        "typesParityReady_true"
        "typesContractParityOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem typesParityReady_true"
        "theorem typesContractParityOk_true"
        "theorem multLinearTypesParityReady_true"
        # Content equality (product API surface; not pure readiness canaries).
        "productTypedIrId_eq"
        "productIrNodeApi_eq"
        "productIrNodeInitApi_eq"
        "productIrNodeIsWellTypedApi_eq"
        "productIrNodeCheckFailClosedApi_eq"
        "productApiSurfaceOk_true"
        "theorem productTypedIrId_eq"
        "theorem productIrNodeApi_eq"
        "theorem productIrNodeInitApi_eq"
        "theorem productIrNodeIsWellTypedApi_eq"
        "theorem productIrNodeCheckFailClosedApi_eq"
        "theorem productApiSurfaceOk_true"
      ];
      anyGroups = [
        [
          "typesParityOk"
          "paritySurfaceOk"
          "productApiSurfaceOk"
        ]
      ];
    }
    {
      # Program / graph / compose self-host kernel (SH4 remainder).
      rel = "src/systems/SystemsLean/KernelProgram.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_PROGRAM_V0"
        "SELF-HOST-KERNEL-PROGRAM"
        "HOST-KERNEL-PROGRAM"
        "SELF-HOST"
        "lowerProgramKernel"
        "programKernelProgram"
        "programKernelReady"
        "programPathReady"
        "programGraphPathReady"
        "programComposePathReady"
        "programKernelOk"
        "SystemsLean.KernelProgram"
        "KERNEL-PROGRAM-SMOKE"
        "example"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "EMPTY-GRAPH-OK"
        "IR-GRAPH-EDGES"
        "HOST-COMPOSE"
        "ORDERED-IR-PROGRAM"
        "HOST-COMPILE-PATH"
        "foldWellTyped"
        "IR_PROGRAM_V0"
        "IR_GRAPH_EDGES_V0"
        "HOST_COMPOSE_V0"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_ir_program"
        "slake_ir_graph"
        "slake_host_compose"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/KernelProgram.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "KERNEL-PROGRAM-THEOREM"
        "HOST-KERNEL-PROGRAM-THEOREM"
        "programKernelReady_true"
        "programKernelOk_true"
        "programCompileReady_empty_false"
        "lowerProgramKernel_length_three"
        "lowerProgramKernel_isWellTyped"
        "programKernelProgram_length_three"
        "programKernelProgram_isWellTyped"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem programKernelReady_true"
        "theorem programKernelOk_true"
        "theorem lowerProgramKernel_length_three"
        "theorem lowerProgramKernel_isWellTyped"
        "theorem programKernelProgram_length_three"
        "theorem programKernelProgram_isWellTyped"
        "theorem programCompileReady_empty_false"
      ];
      anyGroups = [
        [
          "programSurfaceOk"
          "programPathReady"
          "programGraphPathReady"
          "programComposePathReady"
        ]
      ];
    }
    {
      # Program freestanding path parity host + product contracts
      # (Mult+Linear+Types+Program).
      rel = "src/systems/SystemsLean/ParityProgram.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PARITY_PROGRAM_V0"
        "HOST-PARITY-PROGRAM"
        "SELF-HOST-PARITY-PROGRAM"
        "programParityReady"
        "programContractParityOk"
        "multLinearTypesProgramParityReady"
        "SystemsLean.ParityProgram"
        "PARITY-PROGRAM-SMOKE"
        "HOST-PARITY-PROGRAM-SMOKE"
        "example"
        "IR_PROGRAM_V0"
        "IR_GRAPH_EDGES_V0"
        "HOST_COMPOSE_V0"
        "slake_ir_program"
        "slake_ir_program_init"
        "slake_ir_program_push"
        "slake_ir_program_is_well_typed"
        "slake_ir_program_check_fail_closed"
        "slake_ir_graph"
        "slake_ir_graph_init"
        "slake_ir_graph_push_node"
        "slake_ir_graph_add_edge"
        "slake_host_compose"
        "slake_host_compose_init"
        "slake_host_compose_mint"
        "slake_host_compose_consume"
        "programPathReady"
        "programGraphPathReady"
        "programComposePathReady"
        "HOST-KERNEL-PROGRAM"
        "HOST-PARITY-TYPES"
        "HOST-PARITY-LINEAR"
        "HOST-PARITY-MULT"
        "ORDERED-IR-PROGRAM"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/SystemsLean/ParityProgram.lean"
        "UNIT_SURFACE"
        "Not freestanding emit"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "PARITY-PROGRAM-THEOREM"
        "HOST-PARITY-PROGRAM-THEOREM"
        "programParityReady_true"
        "programContractParityOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem programParityReady_true"
        "theorem programContractParityOk_true"
        "theorem multLinearTypesProgramParityReady_true"
        # Content equality (product API surface; not pure readiness canaries).
        "productIrProgramId_eq"
        "productIrGraphId_eq"
        "productHostComposeId_eq"
        "productIrProgramApi_eq"
        "productIrProgramInitApi_eq"
        "productIrProgramPushApi_eq"
        "productIrProgramIsWellTypedApi_eq"
        "productIrProgramCheckFailClosedApi_eq"
        "productIrGraphApi_eq"
        "productIrGraphInitApi_eq"
        "productIrGraphPushNodeApi_eq"
        "productIrGraphAddEdgeApi_eq"
        "productHostComposeApi_eq"
        "productHostComposeInitApi_eq"
        "productHostComposeMintApi_eq"
        "productHostComposeConsumeApi_eq"
        "productApiSurfaceOk_true"
        "theorem productIrProgramId_eq"
        "theorem productIrGraphId_eq"
        "theorem productHostComposeId_eq"
        "theorem productIrProgramApi_eq"
        "theorem productIrProgramInitApi_eq"
        "theorem productIrProgramPushApi_eq"
        "theorem productIrProgramIsWellTypedApi_eq"
        "theorem productIrProgramCheckFailClosedApi_eq"
        "theorem productIrGraphApi_eq"
        "theorem productIrGraphInitApi_eq"
        "theorem productIrGraphPushNodeApi_eq"
        "theorem productIrGraphAddEdgeApi_eq"
        "theorem productHostComposeApi_eq"
        "theorem productHostComposeInitApi_eq"
        "theorem productHostComposeMintApi_eq"
        "theorem productHostComposeConsumeApi_eq"
        "theorem productApiSurfaceOk_true"
      ];
      anyGroups = [
        [
          "programParityOk"
          "paritySurfaceOk"
          "productApiSurfaceOk"
        ]
      ];
    }
    {
      # Freestanding codegen host honesty (SH4 remainder: plan/apply/body).
      rel = "src/systems/SystemsLean/KernelEmit.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_KERNEL_EMIT_V0"
        "SELF-HOST-KERNEL-EMIT"
        "HOST-KERNEL-EMIT"
        "SELF-HOST"
        "lowerEmitCompose"
        "emitHost"
        "emitKernelReady"
        "emitPlanPathReady"
        "emitApplyPathReady"
        "emitBodyPathReady"
        "emitKernelOk"
        "SystemsLean.KernelEmit"
        "KERNEL-EMIT-SMOKE"
        "example"
        "EMIT-PLAN"
        "EMIT-APPLY"
        "EMIT-BODY"
        "HOST-EMIT-SSOT"
        "HOST-EMIT-MULT"
        "HOST-KERNEL-PROGRAM"
        "programKernelReady"
        "emitMultReady"
        "planOk"
        "applyOk"
        "bodyOk"
        "EMIT_PLAN_V0"
        "EMIT_APPLY_V0"
        "EMIT_BODY_V0"
        "RUNTIME-FS"
        "FAIL-CLOSED"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_emit_plan"
        "slake_emit_apply"
        "slake_emit_body"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/KernelEmit.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "KERNEL-EMIT-THEOREM"
        "HOST-KERNEL-EMIT-THEOREM"
        "emitKernelReady_true"
        "emitKernelOk_true"
        "emitPlanPathReady_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem emitKernelReady_true"
        "theorem emitKernelOk_true"
        "theorem emitPlanPathReady_true"
      ];
      anyGroups = [
        [
          "emitSurfaceOk"
          "emitPlanPathReady"
          "emitApplyPathReady"
          "emitBodyPathReady"
        ]
      ];
    }
    {
      # Emit freestanding path parity host + product contracts
      # (Mult+Linear+Types+Program+Emit).
      rel = "src/systems/SystemsLean/ParityEmit.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PARITY_EMIT_V0"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "emitParityReady"
        "emitContractParityOk"
        "multLinearTypesProgramEmitParityReady"
        "SystemsLean.ParityEmit"
        "PARITY-EMIT-SMOKE"
        "HOST-PARITY-EMIT-SMOKE"
        "example"
        "EMIT_PLAN_V0"
        "EMIT_APPLY_V0"
        "EMIT_BODY_V0"
        "HOST-EMIT-SSOT"
        "HOST-EMIT-MULT"
        "slake_emit_plan"
        "slake_emit_plan_id"
        "slake_emit_plan_from_compose"
        "slake_emit_plan_is_ready"
        "slake_emit_apply"
        "slake_emit_apply_id"
        "slake_emit_apply_from_compose"
        "slake_emit_apply_is_valid"
        "slake_emit_body"
        "slake_emit_body_id"
        "slake_emit_body_from_compose"
        "slake_emit_body_is_valid"
        "emitPlanPathReady"
        "emitApplyPathReady"
        "emitBodyPathReady"
        "emitMultReady"
        "HOST-KERNEL-EMIT"
        "HOST-PARITY-PROGRAM"
        "HOST-PARITY-TYPES"
        "HOST-PARITY-LINEAR"
        "HOST-PARITY-MULT"
        "RUNTIME-FS"
        "FAIL-CLOSED"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/SystemsLean/ParityEmit.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "PARITY-EMIT-THEOREM"
        "HOST-PARITY-EMIT-THEOREM"
        "emitParityReady_true"
        "emitContractParityOk_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem emitParityReady_true"
        "theorem emitContractParityOk_true"
        "theorem multLinearTypesProgramEmitParityReady_true"
        # Content equality (product API surface; not pure readiness canaries).
        "productEmitPlanId_eq"
        "productEmitApplyId_eq"
        "productEmitBodyId_eq"
        "productHostEmitSsotId_eq"
        "productHostEmitMultId_eq"
        "productEmitPlanApi_eq"
        "productEmitPlanIdApi_eq"
        "productEmitPlanFromComposeApi_eq"
        "productEmitPlanIsReadyApi_eq"
        "productEmitApplyApi_eq"
        "productEmitApplyIdApi_eq"
        "productEmitApplyFromComposeApi_eq"
        "productEmitApplyIsValidApi_eq"
        "productEmitBodyApi_eq"
        "productEmitBodyIdApi_eq"
        "productEmitBodyFromComposeApi_eq"
        "productEmitBodyIsValidApi_eq"
        "productApiSurfaceOk_true"
        "theorem productEmitPlanId_eq"
        "theorem productEmitApplyId_eq"
        "theorem productEmitBodyId_eq"
        "theorem productHostEmitSsotId_eq"
        "theorem productHostEmitMultId_eq"
        "theorem productEmitPlanApi_eq"
        "theorem productEmitPlanIdApi_eq"
        "theorem productEmitPlanFromComposeApi_eq"
        "theorem productEmitPlanIsReadyApi_eq"
        "theorem productEmitApplyApi_eq"
        "theorem productEmitApplyIdApi_eq"
        "theorem productEmitApplyFromComposeApi_eq"
        "theorem productEmitApplyIsValidApi_eq"
        "theorem productEmitBodyApi_eq"
        "theorem productEmitBodyIdApi_eq"
        "theorem productEmitBodyFromComposeApi_eq"
        "theorem productEmitBodyIsValidApi_eq"
        "theorem productApiSurfaceOk_true"
      ];
      anyGroups = [
        [
          "emitParityOk"
          "paritySurfaceOk"
          "productApiSurfaceOk"
        ]
      ];
    }
    {
      # Compiler self-application readiness (SH5 partial).
      rel = "src/systems/SystemsLean/SelfApply.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_SELF_APPLY_V0"
        "HOST-SELF-APPLY"
        "SELF-HOST-SELF-APPLY"
        "SELF-HOST"
        "selfApplyReady"
        "kernelRebuildsKernel"
        "multKernelSideReady"
        "linearKernelSideReady"
        "typesKernelSideReady"
        "programKernelSideReady"
        "emitKernelSideReady"
        "selfApplyOk"
        "SystemsLean.SelfApply"
        "SELF-APPLY-SMOKE"
        "HOST-SELF-APPLY-SMOKE"
        "example"
        "HOST-PARITY-MULT"
        "SELF-HOST-KERNEL-LINEAR"
        "SELF-HOST-KERNEL-TYPES"
        "SELF-HOST-KERNEL-PROGRAM"
        "SELF-HOST-KERNEL-EMIT"
        "multParityReady"
        "linearKernelReady"
        "typesKernelReady"
        "programKernelReady"
        "emitKernelReady"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/SelfApply.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "SELF-APPLY-THEOREM"
        "HOST-SELF-APPLY-THEOREM"
        "selfApplyReady_true"
        "kernelRebuildsKernel_true"
        "selfApplySurfaceOk_true"
        "selfApplyOk_eq_ready"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem selfApplyReady_true"
        "theorem kernelRebuildsKernel_true"
        "theorem selfApplySurfaceOk_true"
        "theorem selfApplyOk_eq_ready"
      ];
      anyGroups = [
        [
          "selfApplySurfaceOk"
          "kernelRebuildsKernel"
        ]
      ];
    }
    {
      # Freestanding self-application deepen (SH5 freestanding deepen partial).
      # Fail-closed pins: freestandingProductSelfHostComplete must remain := false.
      # Composes freestanding Mult..Emit parity ladder (ParityEmit) into readiness.
      rel = "src/systems/SystemsLean/SelfApplyFs.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_SELF_APPLY_FS_V0"
        "HOST-SELF-APPLY-FS"
        "SELF-HOST-SELF-APPLY-FS"
        "SELF-HOST"
        "freestandingExtractPathReady"
        "freestandingBodyPathReady"
        "freestandingSelfApplyPathReady"
        "freestandingParityLadderReady"
        "freestandingEmitParityReady"
        "freestandingSelfApplyReady"
        "freestandingProductSelfHostComplete"
        "selfApplyFsDoesNotComplete"
        "selfApplyFsOk"
        "SystemsLean.SelfApplyFs"
        "SELF-APPLY-FS-SMOKE"
        "HOST-SELF-APPLY-FS-SMOKE"
        "example"
        "HOST-SELF-APPLY"
        "selfApplyReady"
        "HOST-PARITY-EMIT"
        "SELF-HOST-PARITY-EMIT"
        "SLAKE_SELF_HOST_PARITY_EMIT_V0"
        "emitParityReady"
        "multLinearTypesProgramEmitParityReady"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "HOST-EMIT-SSOT"
        "EMIT_BODY_V0"
        "HOST-EMIT-MULT"
        "SELF-HOST-KERNEL-EMIT"
        "lowerEmitCompose"
        "extractOkFs"
        "bodyOk"
        "emitMultReady"
        "import SystemsLean.ParityEmit"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/SelfApplyFs.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        # Complete-claim pin (presence fail-closed without Lake): def + smoke.
        "def freestandingProductSelfHostComplete : Bool := false"
        "example : freestandingProductSelfHostComplete = false"
        "example : freestandingSelfApplyReady = true"
        "example : selfApplyFsDoesNotComplete = true"
        "example : freestandingParityLadderReady = true"
        "example : freestandingEmitParityReady = true"
        # Structural compose pin: readiness must fold Mult..Emit parity ladder
        # (name tokens alone can survive if the conjunct is dropped from the def).
        "&& freestandingParityLadderReady"
        "SELF-APPLY-FS-THEOREM"
        "HOST-SELF-APPLY-FS-THEOREM"
        "freestandingSelfApplyReady_true"
        "freestandingProductSelfHostComplete_false"
        "selfApplyFsDoesNotComplete_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem freestandingSelfApplyReady_true"
        "theorem freestandingProductSelfHostComplete_false"
        "theorem selfApplyFsDoesNotComplete_true"
      ];
      anyGroups = [
        [
          "selfApplyFsSurfaceOk"
          "freestandingSelfApplyPathReady"
          "freestandingParityLadderReady"
        ]
      ];
    }
    {
      # llvm / PROVABLY hold gate (SH6 held, documented -- not unlock).
      # Fail-closed pins: unlock/complete defs must remain := false (not name-only).
      rel = "src/systems/SystemsLean/LlvmHold.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_LLVM_HOLD_V0"
        "HOST-LLVM-HOLD"
        "SELF-HOST-LLVM-HOLD"
        "HOST-PROVABLY-HOLD"
        "SELF-HOST"
        "llvmHoldReady"
        "sh6HoldReady"
        "llvmUnlocked"
        "provablyUnlocked"
        "freestandingProductSelfHostComplete"
        "selfApplyDoesNotUnlockLlvm"
        "holdHonestyOk"
        "llvmHoldOk"
        "SystemsLean.LlvmHold"
        "LLVM-HOLD-SMOKE"
        "HOST-LLVM-HOLD-SMOKE"
        "example"
        "HOST-SELF-APPLY"
        "selfApplyReady"
        "src/systems/self-host.md"
        "src/systems/SystemsLean/LlvmHold.lean"
        "out/llvm-ir"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        # Hold-contract pins (presence fail-closed without Lake): defs + smoke.
        "def llvmUnlocked : Bool := false"
        "def provablyUnlocked : Bool := false"
        "def freestandingProductSelfHostComplete : Bool := false"
        "example : llvmUnlocked = false"
        "example : provablyUnlocked = false"
        "example : freestandingProductSelfHostComplete = false"
        "example : llvmHoldReady = true"
        "example : sh6HoldReady = true"
        "LLVM-HOLD-THEOREM"
        "HOST-LLVM-HOLD-THEOREM"
        "llvmHoldReady_true"
        "llvmUnlocked_false"
        "provablyUnlocked_false"
        "sh6HoldReady_eq_llvmHoldReady"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem llvmHoldReady_true"
        "theorem llvmUnlocked_false"
        "theorem provablyUnlocked_false"
        "theorem sh6HoldReady_eq_llvmHoldReady"
      ];
      anyGroups = [
        [
          "llvmHoldSurfaceOk"
          "holdHonestyOk"
        ]
      ];
    }
    {
      # Host inventory close readiness (after Mult..Emit parity + SelfApplyFs + SH6 hold).
      # Fail-closed pins: residual free / complete / unlock claims must remain false.
      # Structural compose pins: readiness must fold freestandingSelfApplyReady +
      # llvmHoldReady (name tokens alone can survive if conjuncts are dropped).
      rel = "src/systems/SystemsLean/InventoryClose.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_INVENTORY_CLOSE_V0"
        "HOST-INVENTORY-CLOSE"
        "SELF-HOST-INVENTORY-CLOSE"
        "SELF-HOST"
        "inventoryCloseReady"
        "inventoryCloseSurfaceOk"
        "inventoryPartialCarryHonest"
        "inventoryCloseDoesNotMeanResidualFree"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "inventoryCloseOk"
        "SystemsLean.InventoryClose"
        "INVENTORY-CLOSE-SMOKE"
        "HOST-INVENTORY-CLOSE-SMOKE"
        "example"
        "HOST-SELF-APPLY-FS"
        "HOST-LLVM-HOLD"
        "CLOSABLE-MISS-COUNT-0"
        "HOST-PARTIAL-INVENTORY"
        "intentional PARTIAL"
        "freestandingSelfApplyReady"
        "llvmHoldReady"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/InventoryClose.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : inventoryCloseReady = true"
        "example : inventoryCloseDoesNotMeanResidualFree = true"
        "example : inventoryPartialCarryHonest = true"
        # Structural compose pins: readiness must fold FS self-apply + llvm hold.
        "SelfApplyFs.freestandingSelfApplyReady"
        "LlvmHold.llvmHoldReady"
        "&& inventoryCloseSurfaceOk"
        "&& inventoryPartialCarryHonest"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        "INVENTORY-CLOSE-THEOREM"
        "HOST-INVENTORY-CLOSE-THEOREM"
        "inventoryCloseReady_true"
        "residualFreeClaimed_false"
        "inventoryCloseDoesNotMeanResidualFree_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem inventoryCloseReady_true"
        "theorem residualFreeClaimed_false"
        "theorem inventoryCloseDoesNotMeanResidualFree_true"
      ];
      anyGroups = [
        [
          "inventoryCloseSurfaceOk"
          "inventoryPartialCarryHonest"
          "inventoryCloseReady"
        ]
      ];
    }
    {
      # Freestanding product path readiness (after HOST-INVENTORY-CLOSE).
      # Fail-closed pins: residual free / complete / unlock claims stay false.
      # Structural compose pins: readiness must fold inventoryCloseReady + unit
      # path + program path + emit path + join unit + join program + self-host
      # unit + self-host program + matrix unit + matrix program + surface
      # (name tokens alone can survive if dropped).
      rel = "src/systems/SystemsLean/ProductPath.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PRODUCT_PATH_V0"
        "HOST-PRODUCT-PATH"
        "SELF-HOST-PRODUCT-PATH"
        "SLAKE_SELF_HOST_PRODUCT_PATH_CLOSE_V0"
        "HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST-PRODUCT-PATH-CLOSE"
        "SELF-HOST"
        "productPathReady"
        "productPathSurfaceOk"
        "freestandingUnitProductPathReady"
        "freestandingProgramProductPathReady"
        "freestandingEmitProductPathReady"
        "freestandingJoinProductPathReady"
        "freestandingJoinUnitProductPathReady"
        "freestandingJoinProgramProductPathReady"
        "freestandingSelfHostProductPathReady"
        "freestandingSelfHostUnitProductPathReady"
        "freestandingSelfHostProgramProductPathReady"
        "freestandingMatrixUnitProductPathReady"
        "freestandingMatrixProgramProductPathReady"
        "freestandingProductPathReady"
        "productPathDoesNotComplete"
        "productPathDoesNotMeanResidualFree"
        "productPathCloseReady"
        "productPathLadderClosedOk"
        "productPathCloseSurfaceOk"
        "productPathCloseDoesNotMeanResidualFree"
        "productPathFurtherAliasTheaterHeld"
        "productPathCloseOk"
        "structural product path ladder closed"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "productPathOk"
        "SystemsLean.ProductPath"
        "PRODUCT-PATH-SMOKE"
        "HOST-PRODUCT-PATH-SMOKE"
        "PRODUCT-PATH-CLOSE-SMOKE"
        "HOST-PRODUCT-PATH-CLOSE-SMOKE"
        "example"
        "HOST-INVENTORY-CLOSE"
        "HOST-SELF-APPLY-FS"
        "HOST-COMPILE-PATH"
        "HOST-KERNEL-EMIT"
        "HOST-JOIN-MAP"
        "HOST-SELF-HOST"
        "HOST-SURFACE-MATRIX"
        "SLAKE_SELF_HOST_V0"
        "SLAKE_SURFACE_MATRIX_V0"
        "SURFACE-MATRIX"
        "inventoryCloseReady"
        "unitCompileReady"
        "programCompileReady"
        "extractOkFs"
        "lowerEmitCompose"
        "lowerProgramKernel"
        "emitPlanPathReady"
        "emitApplyPathReady"
        "emitBodyPathReady"
        "emitKernelReady"
        "freestandingBodyPathReady"
        "joinUnitCompileReady"
        "joinProgramCompileReady"
        "selfHostUnitReady"
        "selfHostProgramReady"
        "matrixUnitReady"
        "matrixProgramReady"
        "RUNTIME-FS"
        "EMIT-BOUNDARY"
        "EMIT_BODY_V0"
        "HOST-EMIT-SSOT"
        "HOST-EMIT-MULT"
        "EMPTY-PROGRAM-FAIL-CLOSED"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.CompilePath"
        "import SystemsLean.KernelEmit"
        "import SystemsLean.KernelProgram"
        "import SystemsLean.HostCompose"
        "import SystemsLean.IrProgram"
        "import SystemsLean.JoinMap"
        "import SystemsLean.SelfHost"
        "import SystemsLean.SurfaceMatrix"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/ProductPath.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : productPathReady = true"
        "example : productPathDoesNotComplete = true"
        "example : productPathDoesNotMeanResidualFree = true"
        "example : freestandingUnitProductPathReady = true"
        "example : freestandingProgramProductPathReady = true"
        "example : freestandingEmitProductPathReady = true"
        "example : freestandingJoinProductPathReady = true"
        "example : freestandingJoinProgramProductPathReady = true"
        "example : freestandingSelfHostProductPathReady = true"
        "example : freestandingSelfHostProgramProductPathReady = true"
        "example : freestandingMatrixUnitProductPathReady = true"
        "example : freestandingMatrixProgramProductPathReady = true"
        "example : productPathLadderClosedOk = true"
        "example : productPathCloseReady = true"
        "example : productPathCloseDoesNotMeanResidualFree = true"
        "example : productPathFurtherAliasTheaterHeld = true"
        # Structural compose pins: readiness must fold inventory close + paths.
        "InventoryClose.inventoryCloseReady"
        "freestandingUnitProductPathReady"
        "freestandingProgramProductPathReady"
        "freestandingEmitProductPathReady"
        "freestandingJoinProductPathReady"
        "freestandingJoinProgramProductPathReady"
        "freestandingSelfHostProductPathReady"
        "freestandingSelfHostProgramProductPathReady"
        "freestandingMatrixUnitProductPathReady"
        "freestandingMatrixProgramProductPathReady"
        "&& productPathSurfaceOk"
        "&& !residualFreeClaimed"
        "&& !productSelfHostCompleteClaimed"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        # Close compose pins: ladder close folds productPathReady + surface
        # (&& -prefixed so presence fails if conjuncts drop from def body while
        # bare def names remain).
        "productPathReady"
        "&& productPathCloseSurfaceOk"
        "&& productPathFurtherAliasTheaterHeld"
        "CompilePath.unitCompileReady HostCompose.empty"
        "KernelEmit.unmintedEmitCompose"
        "KernelEmit.lowerEmitCompose"
        "KernelProgram.lowerProgramKernel"
        "CompilePath.programCompileReady IrProgram.empty"
        "KernelEmit.emitPlanPathReady"
        "PRODUCT-PATH-THEOREM"
        "HOST-PRODUCT-PATH-THEOREM"
        "productPathReady_true"
        "productPathCloseReady_true"
        "residualFreeClaimed_false"
        "productPathFurtherAliasTheaterHeld_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem productPathReady_true"
        "theorem productPathCloseReady_true"
        "theorem residualFreeClaimed_false"
        "theorem productPathFurtherAliasTheaterHeld_true"
        "KernelEmit.emitApplyPathReady"
        "KernelEmit.emitBodyPathReady"
        "KernelEmit.emitKernelReady"
        "SelfApplyFs.freestandingBodyPathReady"
        "JoinMap.joinUnitCompileReady HostCompose.empty"
        "JoinMap.joinProgramCompileReady IrProgram.empty"
        "SelfHost.selfHostUnitReady HostCompose.empty"
        "SelfHost.selfHostProgramReady IrProgram.empty"
        "SurfaceMatrix.matrixUnitReady HostCompose.empty"
        "SurfaceMatrix.matrixProgramReady IrProgram.empty"
      ];
      anyGroups = [
        [
          "productPathSurfaceOk"
          "freestandingUnitProductPathReady"
          "freestandingProgramProductPathReady"
          "freestandingEmitProductPathReady"
          "freestandingJoinProductPathReady"
          "freestandingJoinProgramProductPathReady"
          "freestandingSelfHostProductPathReady"
          "freestandingSelfHostProgramProductPathReady"
          "freestandingMatrixUnitProductPathReady"
          "freestandingMatrixProgramProductPathReady"
          "productPathReady"
          "productPathCloseReady"
          "productPathLadderClosedOk"
        ]
      ];
    }
    {
      # Dual residual honesty (host elaborator residual vs product residual)
      # after HOST-PRODUCT-PATH-CLOSE. Fail-closed pins: residual free / complete
      # / unlock claims stay false; both residual surfaces remain; neither free.
      # Structural compose pins: dualResidualReady must fold productPathCloseReady
      # + surface + surfacesDistinct (name tokens alone can survive if dropped).
      rel = "src/systems/SystemsLean/DualResidual.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_DUAL_RESIDUAL_V0"
        "HOST-DUAL-RESIDUAL"
        "SELF-HOST-DUAL-RESIDUAL"
        "SELF-HOST"
        "dualResidualReady"
        "dualResidualSurfaceOk"
        "dualResidualSurfacesDistinct"
        "dualResidualDoesNotMeanResidualFree"
        "dualResidualDoesNotForgeEitherFree"
        "hostElaboratorResidualRemains"
        "productResidualRemains"
        "hostElaboratorResidualFreeClaimed"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "dualResidualOk"
        "SystemsLean.DualResidual"
        "DUAL-RESIDUAL-SMOKE"
        "HOST-DUAL-RESIDUAL-SMOKE"
        "example"
        "HOST-PRODUCT-PATH-CLOSE"
        "HOST-INVENTORY-CLOSE"
        "HOST-LLVM-HOLD"
        "HOST-RESIDUAL"
        "PRODUCT-WIRE-RESIDUAL"
        "EMIT-BOUNDARY"
        "RUNTIME-FS"
        "RUNTIME-CLASSIC"
        "productPathCloseReady"
        "inventoryCloseReady"
        "llvmHoldReady"
        "intentional PARTIAL"
        "host elaborator residual remains"
        "product residual remains"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.ProductPath"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/DualResidual.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        "Not host elaborator residual free"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def hostElaboratorResidualRemains : Bool := true"
        "def productResidualRemains : Bool := true"
        "def hostElaboratorResidualFreeClaimed : Bool := false"
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : hostElaboratorResidualRemains = true"
        "example : productResidualRemains = true"
        "example : hostElaboratorResidualFreeClaimed = false"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : dualResidualReady = true"
        "example : dualResidualDoesNotMeanResidualFree = true"
        "example : dualResidualDoesNotForgeEitherFree = true"
        "example : dualResidualSurfacesDistinct = true"
        "example : dualResidualOk = dualResidualReady"
        # Structural compose pins: readiness must fold product path close +
        # dual residual honesty canaries (&& -prefixed where conjuncts must hold).
        "ProductPath.productPathCloseReady"
        "&& dualResidualSurfaceOk"
        "&& dualResidualSurfacesDistinct"
        "&& hostElaboratorResidualRemains"
        "&& productResidualRemains"
        "&& !hostElaboratorResidualFreeClaimed"
        "&& !residualFreeClaimed"
        "&& !productSelfHostCompleteClaimed"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        "DUAL-RESIDUAL-THEOREM"
        "HOST-DUAL-RESIDUAL-THEOREM"
        "dualResidualReady_true"
        "hostElaboratorResidualRemains_true"
        "productResidualRemains_true"
        "residualFreeClaimed_false"
        "dualResidualOk_eq_ready"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem dualResidualReady_true"
        "theorem hostElaboratorResidualRemains_true"
        "theorem productResidualRemains_true"
        "theorem residualFreeClaimed_false"
        "theorem dualResidualOk_eq_ready"
      ];
      anyGroups = [
        [
          "dualResidualSurfaceOk"
          "dualResidualSurfacesDistinct"
          "dualResidualReady"
          "hostElaboratorResidualRemains"
          "productResidualRemains"
        ]
      ];
    }
    {
      # Probe-vs-wire honesty (hosted behavioral probe smoke debt vs product
      # freestanding wire) after HOST-DUAL-RESIDUAL. Fail-closed pins: residual
      # free / complete / unlock claims stay false; probe is smoke debt not wire.
      # Structural compose pins: probeWireReady must fold dualResidualReady +
      # surface + surfacesDistinct (name tokens alone can survive if dropped).
      rel = "src/systems/SystemsLean/ProbeWire.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_PROBE_WIRE_V0"
        "HOST-PROBE-WIRE"
        "SELF-HOST-PROBE-WIRE"
        "SELF-HOST"
        "probeWireReady"
        "probeWireSurfaceOk"
        "probeWireSurfacesDistinct"
        "probeWireDoesNotMeanResidualFree"
        "probeWireDoesNotMeanProductComplete"
        "behavioralProbeIsSmokeDebt"
        "behavioralProbeIsNotProductWire"
        "productWireIsEmitPath"
        "probeDoesNotReplaceProductWire"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "probeWireOk"
        "SystemsLean.ProbeWire"
        "PROBE-WIRE-SMOKE"
        "HOST-PROBE-WIRE-SMOKE"
        "example"
        "HOST-DUAL-RESIDUAL"
        "HOST-PRODUCT-PATH-CLOSE"
        "HOST-INVENTORY-CLOSE"
        "HOST-LLVM-HOLD"
        "EMIT-BOUNDARY"
        "RUNTIME-FS"
        "dualResidualReady"
        "productPathCloseReady"
        "inventoryCloseReady"
        "llvmHoldReady"
        "intentional PARTIAL"
        "hosted behavioral probe is smoke debt"
        "product freestanding wire"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.DualResidual"
        "import SystemsLean.ProductPath"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/smoke/slake_behavioral_probe.c"
        "src/systems/emit/"
        "out/freestanding-c/"
        "src/systems/SystemsLean/ProbeWire.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        "Not host elaborator residual free"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def behavioralProbeIsSmokeDebt : Bool := true"
        "def behavioralProbeIsNotProductWire : Bool := true"
        "def productWireIsEmitPath : Bool := true"
        "def probeDoesNotReplaceProductWire : Bool := true"
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : behavioralProbeIsSmokeDebt = true"
        "example : behavioralProbeIsNotProductWire = true"
        "example : productWireIsEmitPath = true"
        "example : probeDoesNotReplaceProductWire = true"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : probeWireReady = true"
        "example : probeWireDoesNotMeanResidualFree = true"
        "example : probeWireDoesNotMeanProductComplete = true"
        "example : probeWireSurfacesDistinct = true"
        "example : probeWireOk = probeWireReady"
        # Structural compose pins: readiness must fold dual residual +
        # probe-vs-wire honesty canaries (&& -prefixed where conjuncts must hold).
        "DualResidual.dualResidualReady"
        "&& probeWireSurfaceOk"
        "&& probeWireSurfacesDistinct"
        "&& behavioralProbeIsSmokeDebt"
        "&& behavioralProbeIsNotProductWire"
        "&& productWireIsEmitPath"
        "&& probeDoesNotReplaceProductWire"
        "&& !residualFreeClaimed"
        "&& !productSelfHostCompleteClaimed"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        "PROBE-WIRE-THEOREM"
        "HOST-PROBE-WIRE-THEOREM"
        "probeWireReady_true"
        "behavioralProbeIsSmokeDebt_true"
        "residualFreeClaimed_false"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem probeWireReady_true"
        "theorem behavioralProbeIsSmokeDebt_true"
        "theorem residualFreeClaimed_false"
      ];
      anyGroups = [
        [
          "probeWireSurfaceOk"
          "probeWireSurfacesDistinct"
          "probeWireReady"
          "behavioralProbeIsSmokeDebt"
          "behavioralProbeIsNotProductWire"
        ]
      ];
    }
    {
      # Formal spec-proof separation honesty after HOST-PROBE-WIRE. Fail-closed
      # pins: residual free / complete / unlock / proof-complete claims stay
      # false; readable specs stated; proofs do not retire tests/smokes.
      # Structural compose pins: specProofReady must fold probeWireReady +
      # surface + stated surface + proofDoesNotRetireTests (name tokens alone
      # can survive if dropped).
      rel = "src/systems/SystemsLean/SpecProof.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_SPEC_PROOF_V0"
        "HOST-SPEC-PROOF"
        "SELF-HOST-SPEC-PROOF"
        "SELF-HOST"
        "specProofReady"
        "specProofSurfaceOk"
        "specSurfaceStated"
        "proofCompleteClaimed"
        "specDoesNotImplyProofComplete"
        "proofDoesNotRetireTests"
        "specProofDoesNotMeanResidualFree"
        "specProofDoesNotMeanProofComplete"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "specProofOk"
        "SystemsLean.SpecProof"
        "SPEC-PROOF-SMOKE"
        "HOST-SPEC-PROOF-SMOKE"
        "example"
        "HOST-PROBE-WIRE"
        "HOST-DUAL-RESIDUAL"
        "HOST-PRODUCT-PATH-CLOSE"
        "HOST-INVENTORY-CLOSE"
        "HOST-LLVM-HOLD"
        "EMIT-BOUNDARY"
        "RUNTIME-FS"
        "probeWireReady"
        "dualResidualReady"
        "productPathCloseReady"
        "inventoryCloseReady"
        "llvmHoldReady"
        "intentional PARTIAL"
        "readable specification surface stated"
        "proof complete not forged"
        "proofs do not retire tests"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.ProbeWire"
        "import SystemsLean.DualResidual"
        "import SystemsLean.ProductPath"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/SpecProof.lean"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        "Not host elaborator residual free"
        "Not proof complete"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def specSurfaceStated : Bool := true"
        "def proofCompleteClaimed : Bool := false"
        "def proofDoesNotRetireTests : Bool := true"
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : specSurfaceStated = true"
        "example : proofCompleteClaimed = false"
        "example : proofDoesNotRetireTests = true"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : specProofReady = true"
        "example : specProofDoesNotMeanResidualFree = true"
        "example : specProofDoesNotMeanProofComplete = true"
        "example : specDoesNotImplyProofComplete = true"
        "example : specProofOk = specProofReady"
        # Structural compose pins: readiness must fold probe-wire +
        # formal feedback honesty canaries (&& -prefixed where conjuncts must hold).
        "ProbeWire.probeWireReady"
        "&& specProofSurfaceOk"
        "&& specSurfaceStated"
        "&& proofDoesNotRetireTests"
        "&& specDoesNotImplyProofComplete"
        "&& !proofCompleteClaimed"
        "&& !residualFreeClaimed"
        "&& !productSelfHostCompleteClaimed"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        "SPEC-PROOF-THEOREM"
        "HOST-SPEC-PROOF-THEOREM"
        "specProofReady_true"
        "proofCompleteClaimed_false"
        "residualFreeClaimed_false"
        "specSurfaceStated_true"
        "proofDoesNotRetireTests_true"
        # Structural readiness: real theorem forms (AND, not OR anyGroup).
        "theorem specProofReady_true"
        "theorem proofCompleteClaimed_false"
        "theorem residualFreeClaimed_false"
        "theorem specSurfaceStated_true"
        "theorem proofDoesNotRetireTests_true"
      ];
      anyGroups = [
        [
          "specProofSurfaceOk"
          "specSurfaceStated"
          "specProofReady"
          "proofDoesNotRetireTests"
          "specDoesNotImplyProofComplete"
        ]
      ];
    }
    {
      # HOST-SELF-HOST-BODY: defined freestanding compile step (acceptance first).
      # Composes host-owned Mult + Linear emit readiness + freestanding emit
      # stage cite; freestandingProductSelfHostComplete and residual free stay
      # false. Not a Mult..Emit ProductPath / SelfApply readiness re-list.
      rel = "src/systems/SystemsLean/SelfHostBody.lean";
      all = [
        "SYSTEMS_LEAN_HOST"
        "SLAKE_SELF_HOST_BODY_V0"
        "HOST-SELF-HOST-BODY"
        "SELF-HOST-BODY"
        "SELF-HOST"
        "selfHostBodyReady"
        "selfHostBodySurfaceOk"
        "residualFreeClaimed"
        "productSelfHostCompleteClaimed"
        "freestandingProductSelfHostComplete"
        "selfHostBodyDoesNotComplete"
        "selfHostBodyDoesNotMeanResidualFree"
        "selfHostBodyOk"
        "SystemsLean.SelfHostBody"
        "SELF-HOST-BODY-SMOKE"
        "HOST-SELF-HOST-BODY-SMOKE"
        "example"
        "HOST-EMIT-MULT"
        "HOST-EMIT-LINEAR"
        "HOST-EMIT-SSOT"
        "SLAKE_EMIT_FREESTANDING_C_V0"
        "emitMultReady"
        "emitLinearReady"
        "intentional PARTIAL"
        "defined freestanding compile step"
        "freestandingProductSelfHostComplete"
        "llvmUnlocked"
        "provablyUnlocked"
        "import SystemsLean.EmitMult"
        "import SystemsLean.EmitLinear"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "import SystemsLean.DualResidual"
        "src/systems/self-host.md"
        "src/systems/host-partial-inventory.md"
        "src/systems/SystemsLean/SelfHostBody.lean"
        "src/systems/SystemsLean/FreestandingEmit.lean"
        "slake-emit-freestanding-c"
        "out/freestanding-c/"
        "UNIT_SURFACE"
        "Not freestanding residual free"
        "Not PROVABLY"
        "Not freestanding product"
        "Not freestanding emit residual free"
        "Not llvm unlocked"
        "Not host elaborator residual free"
        "Not proof complete"
        # Claim pins (presence fail-closed without Lake): defs + smoke.
        "def residualFreeClaimed : Bool := false"
        "def productSelfHostCompleteClaimed : Bool := false"
        "example : residualFreeClaimed = false"
        "example : productSelfHostCompleteClaimed = false"
        "example : freestandingProductSelfHostComplete = false"
        "example : selfHostBodyReady = true"
        "example : selfHostBodyDoesNotComplete = true"
        "example : selfHostBodyDoesNotMeanResidualFree = true"
        "example : selfHostBodyOk = selfHostBodyReady"
        # Structural compose pins: body path must fold Mult + Linear emit.
        # Complete flag once via SelfApplyFs (local freestandingProductSelfHostComplete
        # is alias; not double-fold theater).
        "EmitMult.emitMultReady"
        "EmitLinear.emitLinearReady"
        "&& selfHostBodySurfaceOk"
        "&& (freestandingEmitStageCite == \"SLAKE_EMIT_FREESTANDING_C_V0\")"
        "&& !residualFreeClaimed"
        "&& !productSelfHostCompleteClaimed"
        "&& !SelfApplyFs.freestandingProductSelfHostComplete"
        "&& !LlvmHold.llvmUnlocked"
        "&& !LlvmHold.provablyUnlocked"
        "SELF-HOST-BODY-THEOREM"
        "HOST-SELF-HOST-BODY-THEOREM"
        "selfHostBodyReady_true"
        "freestandingProductSelfHostComplete_false"
        "residualFreeClaimed_false"
        "selfHostBodyOk_eq_ready"
        "theorem selfHostBodyReady_true"
        "theorem freestandingProductSelfHostComplete_false"
        "theorem residualFreeClaimed_false"
        "theorem selfHostBodyOk_eq_ready"
      ];
      anyGroups = [
        [
          "selfHostBodySurfaceOk"
          "selfHostBodyReady"
          "emitMultReady"
          "emitLinearReady"
          "selfHostBodyDoesNotComplete"
        ]
      ];
    }
    {
      # HOST-EMIT-SSOT durable artifact: empty fragment + dialect keys.
      rel = "src/systems/emit/host_emit_body_fragment.ssot.txt";
      all = [
        "HOST-EMIT-SSOT"
        "EMPTY_FRAGMENT"
        "HEADER_OPEN"
        "HEADER_E"
        "HEADER_CLOSE"
        "TAG_OPEN"
        "TAG_MULT"
        "TAG_KIND"
        "TAG_CLOSE"
        "/* EMIT_BODY_V0 RUNTIME-FS r=0 e=0 */"
        "NON-SSOT"
        "buildFragment"
      ];
    }
    {
      # HOST-EMIT-MULT durable Mult product text (SH2).
      rel = "src/systems/emit/host_emit_mult.ssot.txt";
      all = [
        "HOST-EMIT-MULT"
        "NON-SSOT"
        "SELF-HOST-EMIT-MULT"
        "SLAKE_SELF_HOST_EMIT_MULT_V0"
        "MULT_NAME_0"
        "MULT_NAME_1"
        "MULT_NAME_OMEGA"
        "MULT-0"
        "MULT-1"
        "MULT-OMEGA"
        "slake_mult_is_valid"
        "FAIL-CLOSED-UNKNOWN-GRADE"
        "MULT_C_HEADER_BEGIN"
        "MULT_C_BODY_BEGIN"
        "EmitMult"
      ];
    }
    {
      # HOST-EMIT-LINEAR durable Linear product text.
      rel = "src/systems/emit/host_emit_linear.ssot.txt";
      all = [
        "HOST-EMIT-LINEAR"
        "NON-SSOT"
        "SELF-HOST-EMIT-LINEAR"
        "SLAKE_SELF_HOST_EMIT_LINEAR_V0"
        "LINEAR-EXACT-ONCE"
        "CONSUME_TOKEN_HOST_V0"
        "JOIN-ALG"
        "slake_linear_consume"
        "slake_consume_token_consume"
        "LINEAR_C_HEADER_BEGIN"
        "LINEAR_C_BODY_BEGIN"
        "EmitLinear"
      ];
    }
    {
      rel = "src/systems/SystemsLean.lean";
      all = [
        "import SystemsLean.Mult"
        "import SystemsLean.Linear"
        "import SystemsLean.Types"
        "import SystemsLean.IrProgram"
        "import SystemsLean.Erasure"
        "import SystemsLean.Extract"
        "import SystemsLean.IrGraph"
        "import SystemsLean.HostCompose"
        "import SystemsLean.EmitPlan"
        "import SystemsLean.EmitApply"
        "import SystemsLean.EmitBody"
        "import SystemsLean.CompilePath"
        "import SystemsLean.JoinMap"
        "import SystemsLean.SelfHost"
        "import SystemsLean.SurfaceMatrix"
        "import SystemsLean.KernelMult"
        "import SystemsLean.EmitMult"
        "import SystemsLean.EmitLinear"
        "import SystemsLean.ParityMult"
        "import SystemsLean.KernelLinear"
        "import SystemsLean.ParityLinear"
        "import SystemsLean.KernelTypes"
        "import SystemsLean.ParityTypes"
        "import SystemsLean.KernelProgram"
        "import SystemsLean.ParityProgram"
        "import SystemsLean.KernelEmit"
        "import SystemsLean.ParityEmit"
        "import SystemsLean.SelfApply"
        "import SystemsLean.SelfApplyFs"
        "import SystemsLean.LlvmHold"
        "import SystemsLean.InventoryClose"
        "import SystemsLean.ProductPath"
        "import SystemsLean.DualResidual"
        "import SystemsLean.ProbeWire"
        "import SystemsLean.SpecProof"
        "import SystemsLean.SelfHostBody"
      ];
    }
  ];
}
